name: carkim_var
description: Çarkım Var uygulaması
publish_to: 'none' # local project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
  uses-material-design: true

  assets:
    sdk: flutter
    - assets/ranks/bronze.png
    - assets/ranks/silver.png
    - assets/ranks/gold.png
    - assets/ranks/platinum.png
    - assets/ranks/diamond.png
  google_fonts: ^6.2.1
  flutter_fortune_wheel: ^1.3.0
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+6
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  share_plus: ^11.1.0
  percent_indicator: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/profile_placeholder.png
    - assets/logo.png
    - assets/ranks/bronze.png
    - assets/ranks/silver.png
    - assets/ranks/gold.png
    - assets/ranks/platinum.png
    - assets/ranks/diamond.png